name: Test

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12-dev']
        experimental: [false]
        include:
          - version: '3.12-dev'
            # sets continue-on-error automatically
            experimental: true

    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      # memray doesn't ship 3.12-dev binaries yet
      # https://github.com/bloomberg/memray#building-from-source
      - name: Install memray build dependencies for Python -dev versions
        if: endsWith(matrix.python-version, '-dev') 
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo apt-get install --yes --no-install-recommends libunwind-dev liblz4-dev

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip wheel
            python -m pip install tox tox-gh-actions

      - name: Test with tox
        run: |
          export PYTHONFAULTHANDLER=1
          tox
