name: Test

on:
  pull_request:

permissions: {}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
        experimental: [false]
        include:
          - python-version: '3.15-dev'
            # sets continue-on-error automatically
            experimental: true

    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0

      - name: Setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      # memray sometimes lags on shipping -dev binaries,
      # so install these to build from source when that happens.
      # https://github.com/bloomberg/memray#building-from-source
      - name: Install memray build dependencies for Python -dev versions
        if: endsWith(matrix.python-version, '-dev')
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo apt-get install --yes --no-install-recommends libunwind-dev liblz4-dev libdebuginfod-dev

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip wheel
            python -m pip install tox tox-gh-actions

      - name: Test with tox
        run: |
          export PYTHONFAULTHANDLER=1
          tox
