name: Update starlark-go
on:
  schedule:
    - cron: '59 14 * * 6' 
  workflow_dispatch:

permissions: {}

jobs:
  update-starlark-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: main
          fetch-depth: 0

      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0

      - run: ./scripts/update-starlark.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        if: ${{ env.NEW_STARLARK_VERSION != null && env.NEW_STARLARK_VERSION != '' }}
        # TODO: this permission may not be necessary because of the PR_TOKEN secretâ€¦
        permissions:
          pull_requests: write
        with:
          title: Update starlark-go to ${{ env.NEW_STARLARK_VERSION }}
          commit-message: Update starlark-go to ${{ env.NEW_STARLARK_VERSION }}
          branch: update-starlark-go
          token: ${{ secrets.PR_TOKEN }}
