name: Update starlark-go
on:
  schedule:
    - cron: '59 14 * * 6' 
  workflow_dispatch:

permissions: {}

jobs:
  update-starlark-go:
    runs-on: ubuntu-latest
    # TODO: this permission may not be necessary because of the PR_TOKEN secretâ€¦
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: main
          fetch-depth: 0

      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0

      - run: ./scripts/update-starlark.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        if: ${{ env.NEW_STARLARK_VERSION != null && env.NEW_STARLARK_VERSION != '' }}
        with:
          title: Update starlark-go to ${{ env.NEW_STARLARK_VERSION }}
          commit-message: Update starlark-go to ${{ env.NEW_STARLARK_VERSION }}
          branch: update-starlark-go
          token: ${{ secrets.PR_TOKEN }}
