name: Valgrind

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    name: Valgrind
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: x64

      - name: Install valgrind
        run: |
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install valgrind

      - name: Run valgrind
        run: ./scripts/pytest-valgrind.sh
